language: python
python:
 - "3.5"

# command to run tests
script:
<<<<<<< HEAD
 - python -m unittest TestTriangle1
=======
 - python -m unittest TestTriangle1
>>>>>>> 0a34a4a9e2a24591cd386e7decfcd312aca9ad8b
